export { default as CandidatListPartial } from './CandidatListPartial';
export { default as NewsletterPartial } from './NewsletterPartial';
export { default as ActionPartial } from './ActionPartial';
export { default as DiscoverPartial } from './DiscoverPartial';
export { default as ShareCandidatesCVTutorial } from './ShareCandidatesCVTutorial';
export { default as LandingPagePartial } from './LandingPagePartial';
export { default as NumberPartial } from './NumberPartial';
export { default as SharePartial } from './SharePartial';
export { default as TeasingPartial } from './TeasingPartial';
