export { default as CandidatListPartial } from './CandidatListPartial';
export { default as ContactPartial } from './ContactPartial';
export { default as ContactPartialOld } from './ContactPartial-old';
export { default as ActionPartial } from './ActionPartial';
export { default as DiscoverPartial } from './DiscoverPartial';
export { default as EmphasePartial } from './EmphasePartial';
export { default as LandingPagePartial } from './LandingPagePartial';
export { default as NumberPartial } from './NumberPartial';
export { default as SharePartial } from './SharePartial';
